---
title: "Polling Places"
author: "Paul Dingus"
date: "11/5/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(sf)
library(sp)
library(leaflet)
library(foreign)
library(rgdal)
library(ggplot2)
library(rgeos)
library(raster)
library(tidycensus)

options(tigris_use_cache = TRUE)
```


```{r}
#list of relevant census variable codes:

# B01003_001E Total population
# B02001_002E	White
# B02001_003E	Black or African American
# B02001_004E	American Indian and Alaska Native alone
# B02001_005E	Asian alone
# B02001_006E	Native Hawaiian and Other Pacific Islander alone
# B01001I_001E Hispanic or Latino
# B02001_007E	Some other race alone

#store the population variables we are interested in:
popvars = c(White = "B02001_002E", 
            Black = "B02001_003E")

#pull the relevant ACS data using tidycensus, along with the geography
acs <- get_acs(state = "SC", geography = "tract", variables = popvars, geometry = TRUE, summary_var = "B01003_001", key = "1e1cf42d8641a1710b321c2435820e535645518f")

census <- get_decennial(year = 2020, 
                        state = "SC", 
                        geography = "county", 
                        variables = "P1_001N", 
                        geometry = TRUE, 
                        key = "1e1cf42d8641a1710b321c2435820e535645518f")
```

```{r}
census

census %>%
  ggplot(aes(fill = value)) + 
  geom_sf(color = NA) +
  coord_sf(crs = 4269) +
  scale_fill_viridis_c()
```


## Racial map

```{r}
#plot ACS data
acs %>%
  mutate(pct = 100 * (estimate / summary_est)) %>%
  ggplot(aes(fill = pct)) +
  facet_wrap(~variable) +
  geom_sf(color = NA) +
  coord_sf(crs = 4269) +
  scale_fill_viridis_c()
```

## Centroids

```{r}
#add centroids column
acs = acs %>% mutate(centroid = st_centroid(geometry))

#plot centroids to make sure they look right
acs %>% ggplot() + geom_sf() + geom_sf(data = acs$centroid, colour = "blue", size = 0.1)
```

## Areas

```{r}
#find the area of the geometries
acs = acs %>% mutate(area = st_area(geometry))

#get density
acs = acs %>% mutate(density = summary_est/area)

#get a quick idea of the distribution of densities
ggplot() + geom_histogram(aes(as.numeric(acs$density)))

#store density quantiles so we an bucket them later on
density_quantiles = quantile(as.numeric(acs$density))
```

```{r}
cents_utm = spTransform(cents, CRS("+proj=utm"))
spDists(cents_utm, cents_utm[1])
```



```{r}
#import polling places shapefile and convert to lat long sf
polling_places <- readOGR("./South_Carolina_2018")
polling_places = spTransform(polling_places, CRS("+proj=longlat"))
polling_places = st_as_sf(polling_places)
polling_places = st_transform(polling_places, 4269)

#plot to make sure it looks good:
ggplot() + geom_sf(data = polling_places$geometry, colour = "blue", size = 0.1)
```

```{r}
#calculate distance:
dists = st_distance(acs$centroid[1], polling_places$geometry)
dists[1]
min(dists)

#prime columns to store nearest distance
acs$nearest_polling_place = 1
acs$five_nearest_polling_places = 1

#
for (i in c(1:nrow(acs))) {
  #find distances
  dists = st_distance(acs$centroid[i], polling_places$geometry)
  
  #find closest polling place
  acs$nearest_polling_place[i] = as.numeric(min(dists))
  
  #find average of 5 nearest polling places
  acs$five_nearest_polling_places[i] = mean(as.numeric(sort(dists)[1:5]))
}
```


```{r}
acs %>%
  ggplot(aes(fill = nearest_polling_place)) +
  geom_sf(color = NA) +
  coord_sf(crs = 4269) +
  scale_fill_viridis_c()
```

```{r}
acs_percentage = na.omit(
  acs %>% 
  filter(variable == "B02001_003") %>% 
  mutate(percent_black = estimate/summary_est)
  )

cor(acs_percentage$percent_black, acs_percentage$nearest_polling_place)
cor(acs_percentage$percent_black, acs_percentage$five_nearest_polling_places)

density_quantiles = quantile(as.numeric(acs_percentage$density))

for (i in 1:4) {
  quantile = acs_percentage %>% 
    filter(as.numeric(density) >= as.numeric(density_quantiles[i]), as.numeric(density) <= as.numeric(density_quantiles[i+1]))
  print(cor(quantile$percent_black, quantile$nearest_polling_place))
}
```


```{r}
acs

acs %>% 
 group_by(GEOID) %>% 
 summarise_all(funs(trimws(paste(., collapse = ''))))
```

```{r}
# might be differences in the extremes of density

# polling places metric

# regression variables:
# race
# density
# age
# income
# education

acs_percentage %>% ggplot() + geom_point(aes(density, percent_black))
```



